[package]
name = "vanity_gpg"
version = "0.1.0"
edition = "2018"
authors = ["Kay Lin <i@v2bv.net>"]
description = "A simple tool for generating and filtering vanity GPG keys, c0nCurr3nt1Y"
homepage = "https://github.com/RedL0tus/VanityGPG"
repository = "https://github.com/RedL0tus/VanityGPG"
keywords = [ "GPG", "Vanity", "VanityGPG" ]
readme = "README.md"
license = "MIT"
categories = [ "command-line-utilities" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "^0.4", features = [ "std" ] }
clap = "3.0.0-beta.1"
gpgme = "^0.9"
regex = "^1.3"
anyhow = "^1.0"
colored = "^1.9"
indicatif = "^0.14"
lazy_static = "^1.4"
