name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install dependencies
      run: sudo apt-get install nettle-dev libssl-dev capnproto make clang pkg-config libsqlite3-dev llvm libclang-dev
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features --release --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --release --verbose
